---
title: "class16_hw"
author: Emily Chases (PID A14656894)
format: pdf
---


```{r}
# BiocManager::install("tximport")

library(tximport)

# setup the folder and filenames to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```


```{r}
head(txi.kallisto$counts)

```


```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts)>0)
```
FILTER 
```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```


```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)

```


```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```

ggplot to make this pca plot

```{r}
library(ggplot2)

ggplot(pca$x) + aes(x=PC1, y=PC2, ) + geom_point(col=c("blue","blue","red","red"))
```

```{r}
ggplot(pca$x) + aes(x=PC1, y=PC3, ) + geom_point(col=c("blue","blue","red","red"))
```

```{r}
ggplot(pca$x) + aes(x=PC2, y=PC3, ) + geom_point(col=c("blue","blue","red","red"))
```

